### ISSUE TITLE
Zou het bij de animatie van het formulier kunnen helpen als je een Transition ipv een Keyframe Animation gebruikt?`

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/the-startup-responsive-interactieve-website#32]

**Comment by SamaraFellaDina** [comment]
Ik heb er even naar gekeken, maar ik krijg het nog niet aan de praat. Alhoewel ik de feedback zeker begrijp. Ik had hier beter een `transition` kunnen gebruiken. Er zit alleen al javascript aan vast en dergelijke. Als ik er aan toe kom kijk ik er naar :)

Ik probeerde deze code, alleen werkte het niet.

```css
.download-form .download-form-complete-in {
    opacity: 0;
    transition-property: opacity;
    transition-duration: 1s;
    transition-delay: 0.3s;
}
```
